inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'notes/**/*'

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
